site_name: Scons.Gbd.Docs
site_url: http://ASoftTech.github.io/Scons.Gbd.Docs
repo_url: https://github.com/ASoftTech/Scons.Gbd.Docs
site_description: Scons.Gbd.Docs - scons related tools for documentation
edit_uri: edit/master/docs/MkDocs/docs

pages:
- Home: index.md

- Builders:
    - Mkdocs:
        - MkDocs Config: Builders\Mkdocs\MkdocsConfig.md
        - MkDocs Builder: Builders\Mkdocs\MkdocsBuild.md
#        - MkDocs Publish: Builders\Mkdocs\MkdocsPublish.md
#        - MkDocs Server: Builders\Mkdocs\MkdocsServer.md
#        - MkDocs Combiner: Builders\Mkdocs\MkdocsCombiner.md
- Development:
    - Overall Setup: Development\Setup.md
    - Python Environments: Development\VirtualEnv.md
    - Testing: Development\Testing.md
    - Jinja Templates: Development\Templates.md
    - Using devel Scons: Development\SconsDevelop.md
    - Todo: Development\Todo.md
#    - Plugin: Development\Plugin.md


#theme: cosmo
theme: cyborg
#theme: alabaster
#theme: readthedocs
#theme: mkdocs
#theme: material

# Overrides content within the selected theme
custom_dir: theme

markdown_extensions:
    - smarty

extra_css:
    - css/highlight-fix.css
    - css/highlight-custom.css
    - css/navbarfix.css